### ISSUE TITLE
SSL CERTIFICATE FAILED

### ISSUE THREAD

**Issue by chango73** [tempestsecurity/MISP-Broker#1]
Hello,
I have a MISP with self signed certificate. I have uploaded the root CA on MISP-Broker but I got the SSL CERTIFICATE ERROR.
_

> SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain

_

How can I solve the issue?
Thank you

**Comment by moacir-bezerra** [comment]
> Hello, I have a MISP with self signed certificate. I have uploaded the root CA on MISP-Broker but I got the SSL CERTIFICATE ERROR. _
> 
> > SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain
> 
> _
> 
> How can I solve the issue? Thank you

Hello @chango73, thanks for testing our tool!

You tried to change the MISP_VERIFY_SSL to False in configs/...cfg ?

We are waiting for your confirmation that it worked.
Your feedback is very important to us.
Thank you!

**Comment by chango73** [comment]
Hello,
I changed the value to False but i got the following error.

`timestamp="2023-07-05 12:39:59,851" severity="INFO" func="agent" mode="AGENT" type="ip-src" earliest="2023-06-06 00:00:00" latest="2023-06-12 23:59:59" hour_count="168" total_hours="720" details="Trying to connect to MISP server"
timestamp="2023-07-05 12:39:59,851" severity="INFO" func="agent" mode="AGENT" type="ip-src" earliest="2023-06-06 00:00:00" latest="2023-06-12 23:59:59" hour_count="168" total_hours="720" details="Starting requests" URL="https://"fqdn"/attributes/restSearch"
timestamp="2023-07-05 12:39:59,977" severity="ERROR" func="connection_error_register" details="Connection error" value="(True, [(18835, 'MISP', '2023-07-05 12:39:59', 'mode='AGENT' type='ip-src' earliest='2023-06-06 00:00:00' latest='2023-06-12 23:59:59' hour_count='168' total_hours='720' details='Cannot connect to MISP server' value='https://"fqdn"/attributes/restSearch HTTPSConnectionPool(host=\'"fqdn"\', port=443): Max retries exceeded with url: /attributes/restSearch (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:997)\')))'')])"

`

**Comment by chango73** [comment]
hello,
after reboot the issue is not present.
Thank you.
